### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [gvtulder/joseph-conrad_a-personal-record#1]
# preface-1.xhtml:

- [x] In the `<footer>` element, move the `z3998:signature` semantic to the surrounding `<p>` element.

# preface-2.xhtml:

- [x] In the `<footer>` element, move the `z3998:signature` semantic to the surrounding `<p>` element.

# chapter-1.xhtml:

- [x] In "That which in their grownup years may appear...", `grownup` needs to be `grown-up`. This word is an adjective. Make sure this is restored in an [Editorial] commit.

# chapter-2.xhtml:

- [x] Remove italics from `Officier d’Ordonnance`. Non-English words that are proper names are not italicized ([SEMOS 8.2.9.2](https://standardebooks.org/manual/1.8.1/single-page#8.2.9.2)).

- [x] Remove italics from `Virtuti Militari`.

# chapter-5.xhtml:

- [ ] Remove italics around `par excellence`. It is in MW.

- [x] Remove italics around `encore`. It is in MW.

- [x] `<abbr epub:type="z3998:name-title">M.</abbr>` elements need a no-break space between the abbreviation and its target.

# chapter-6.xhtml:

- [x] Replace `<b>` with `<strong>`.

- [x] `<abbr epub:type="z3998:name-title">M.</abbr>` elements need a no-break space between the abbreviation and its target.

# chapter-7.xhtml:

- [x] Remove italics from `Vieux Port`.

# local.css:

- [x] The `z3998:signature` semantic needs the corresponding CSS:
```
[epub|type~="z3998:signature"]{
	font-variant: small-caps;
}
```

# content.opf:

- [x] The short description should not have any proper nouns.

**Comment by gvtulder** [comment]
Thanks. I fixed most of the issues, with a few remaining remarks:

* **Italics around `par excellence`**: This is indeed in MW, but the phrase also appears in the `se lint` [list of exceptions](https://github.com/standardebooks/tools/blob/55e92f67a90930cdfbceb4ed97a81ca06cb3bcf4/se/se_epub_lint.py#L2715-L2721) and generates an error if it's not in italics. I've left it unchanged for now.
  
* **Italics around `encore`**: I noticed this, but kept it in italics because it seemed to be part of a sequence of French words and phrases. I am not entirely sure why the French words are here, they're not exactly a sentence, but they look like they belong together:
   ![italics](https://github.com/user-attachments/assets/307201a3-517f-4294-bc40-3f1fc94261c4)
   I've removed the italics from `encore` as suggested, but for symmetry it might be nicer to keep it. If you think this should be reverted, let me know.
  
* **Replace `<b>` with `<strong>`**: I haven't changed this yet. In the book, the word `SOBER` is printed in small caps:
   ![smallcaps](https://github.com/user-attachments/assets/03b4e4e4-f930-447f-a380-2a7f639a760f)
   From [SEMoS 4.1.2.3](https://standardebooks.org/manual/1.8.1/single-page#4.1.2.3) and the example in [SEMoS 8.3.3](https://standardebooks.org/manual/1.8.1/single-page#8.3.3) I understood that `<b>` can be used to format this. Alternatively, quotes might work: `the very word "sober"`. I don't think `<strong>` would make sense here, as that would make it really conspicuous.

* **For the footer**: I fixed this, but it might be good to mention that I reused the footer formatting I found in Conrad's [Under Western Eyes](https://github.com/standardebooks/joseph-conrad_under-western-eyes/blob/master/src/epub/text/preface.xhtml), so this might need to be changed there as well. (I also used it for [The Mirror of the Sea](https://github.com/standardebooks/joseph-conrad_the-mirror-of-the-sea).)

**Comment by EmmaSweeney** [comment]
> Italics around par excellence: This is indeed in MW, but the phrase also appears in the se lint [list of exceptions](https://github.com/standardebooks/tools/blob/55e92f67a90930cdfbceb4ed97a81ca06cb3bcf4/se/se_epub_lint.py#L2715-L2721) and generates an error if it's not in italics. I've left it unchanged for now.

That's fine. The [manual's list of italics exceptions](https://standardebooks.org/manual/1.8.1/single-page#8.2.9.9) doesn't have that listed, and I don't have the list in the tools memorized.

> Replace `<b>` with `<strong>`: I haven't changed this yet. In the book, the word `SOBER` is printed in small caps:
> From [SEMoS 4.1.2.3](https://standardebooks.org/manual/1.8.1/single-page#4.1.2.3) and the example in [SEMoS 8.3.3](https://standardebooks.org/manual/1.8.1/single-page#8.3.3) I understood that `<b>` can be used to format this. Alternatively, quotes might work: the very word "sober". I don't think `<strong>` would make sense here, as that would make it really conspicuous.

`<b>` is usually used for appearances, like signs. Good chunk of chapter 6 is about sobriety. In the text, the author is emphasizing the word sober, because he faces life without illusions and with a sense of duty and seriousness. `<strong>` is used for any form of emphasis, not just for yelling.

> For the footer: I fixed this, but it might be good to mention that I reused the footer formatting I found in Conrad's [Under Western Eyes](https://github.com/standardebooks/joseph-conrad_under-western-eyes/blob/master/src/epub/text/preface.xhtml), so this might need to be changed there as well. (I also used it for [The Mirror of the Sea](https://github.com/standardebooks/joseph-conrad_the-mirror-of-the-sea).)

You can make pull requests with the corrections.

**Comment by gvtulder** [comment]
OK, changed `<b>` to `<strong>` now.
